-- Execute isso no SQL Editor do Supabase

-- Cria a tabela work_orders
CREATE TABLE public.work_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asset TEXT NOT NULL,
  type TEXT NOT NULL,
  priority TEXT NOT NULL,
  status TEXT NOT NULL,
  responsible TEXT NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  execution_notes TEXT,
  rejection_reason TEXT,
  closure_notes TEXT
);

-- Ativa Row Level Security (RLS)
ALTER TABLE public.work_orders ENABLE ROW LEVEL SECURITY;

-- Permitiremos que qualquer usuário autenticado leia, insira e atualize as ordens.
-- Em produção, você adicionaria regras mais restritas (ex: só o técnico responsável pode atualizar).
CREATE POLICY "Ordens são visíveis para todos os usuários autenticados" 
ON public.work_orders FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Usuários autenticados podem inserir ordens" 
ON public.work_orders FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Usuários autenticados podem atualizar ordens" 
ON public.work_orders FOR UPDATE USING (auth.role() = 'authenticated');
